### ISSUE TITLE
seed phrase, MetaMask 3.14.1

### ISSUE THREAD

**Issue by Entitie** [MetaMask/vault-decryptor#11]
Hi there. I ran into a problem, metamask 3.14 does not connect, I do not have a phrase. In this issue https://github.com/MetaMask/metamask-extension/issues/10205, a person also has opera and metamask 3.14. 
And he managed to solve the problem somehow.
In which local files did he find the "data" and decrypt it?
:\Users\user\AppData\Roaming\Opera Software\Opera Stable\Extensions\keoanijiealjeplfaflkcgijnnflaine\3.14.1_0\ ???
manifest.json?
"key"?

**Comment by nem1131** [comment]
![image_2021-03-11_12-03-15](https://user-images.githubusercontent.com/40797709/110762940-681bf280-8262-11eb-9889-e1eee48606a1.png)
Hi there man! I've done it the next way. You should open your goddamn notworking metamask from Dan Finlay (Thank him for not reply in twitter) then right-click on it and open dev tools mode. Choose "application" tab, left-click "metamask-config" and then find "KeyringController" in bottom window. Infromation that you're looking for will be there.

**Comment by Entitie** [comment]
Thanks a lot, man. You are the best! =)
