### ISSUE TITLE
decrypting without the password

### ISSUE THREAD

**Issue by m11ad** [MetaMask/vault-decryptor#19]
I have the vault data but I don't have the password, how should I proceed?

**Comment by Weak04** [comment]
My meta mask hacked iwant to recover I don't have phrae

**Comment by bryanhsu7** [comment]
I have the vault data but I don't have the password, how should I proceed?

**Comment by mcmire** [comment]
Sorry, but we don't offer support through GitHub. For help, please see: https://metamask.zendesk.com/hc/en-us
