### ISSUE TITLE
Lost my two words in seed phase Asap😢

### ISSUE THREAD

**Issue by Brianlexter** [MetaMask/vault-decryptor#26]

**Comment by 3rdIteration** [comment]
two missing words is no problem if you use something like btcrecover: https://github.com/3rdIteration/btcrecover

Just run the tool totally offline. (So disable all networking, etc, and only re-enable after you have recovered the seed and moved the funds to a new wallet)

**Comment by mcmire** [comment]
Sorry, but we don't offer support through GitHub. For help, please see: https://metamask.zendesk.com/hc/en-us
