### ISSUE TITLE
Decrypter giving a bunch of numbers

### ISSUE THREAD

**Issue by christinaH272** [MetaMask/vault-decryptor#27]
Decrypter is now giving a bunch of numbers instead of the actual seed. Tested on multiple active and new metamask's.

**Comment by Bozzman12** [comment]
Did the same thing to me as well

**Comment by 3rdIteration** [comment]
I had reports of this too, have applied a fix to BTCRecover's decrypt/dump function.

See here: https://github.com/3rdIteration/btcrecover/commit/fe7cb9d55b58c121bc75ba0644b0221591290211

**Comment by mcmire** [comment]
This should be fixed now. Please let us know if you notice any other issues!
