### ISSUE TITLE
 "How to Copy Your Vault Data" not loading

### ISSUE THREAD

**Issue by 0xRedman** [MetaMask/vault-decryptor#3]
I am trying to use the Vault Decryptor to recover my account after I could not find my seed phrase when my browser was restarted and I got logged out of metamask. I try going to the "How to Copy Your Vault Data" website and I receive a "Page not Found" error.

I am lost and don't know what to do.

**Comment by danfinlay** [comment]
Sorry, our knowledge base was moved to here: http://metamask.consensyssupport.happyfox.com/home

You should be able to find what you seek there.

**Comment by 0xRedman** [comment]
I tried this and it gives me the more recent "account" made on metamask. Is there any way to recover an older account that I had made? 

I had that account open on my browser before, the computer restarted and I was logged out. I did "create an account" hoping that it would help. I'm following the vault recovery instructions and it only gives me the seed for that new account. Is there anything I can do??

**Comment by danfinlay** [comment]
Do you have the seed phrase for the old account?

**Comment by 0xRedman** [comment]
No, I don't. There's no way to recover it from my browser data?

**Comment by danfinlay** [comment]
Yes, you can extract your vault from your browser:
http://metamask.helpscoutdocs.com/article/22-how-to-copy-your-vault-data

And you can parse it to get your seed phrase with this tool (beware of any tool that involves posting your private info! I could be a phisher! At least this one is hosted on the official MetaMask github):
https://metamask.github.io/vault-decryptor/
