### ISSUE TITLE
decryptor giving some numbers instead of seed phrase

### ISSUE THREAD

**Issue by sphynixdc** [MetaMask/vault-decryptor#32]
long story short, I am trying to decrypt a metamask vault from a brave browser file.

I have the {"data":"... string and the decryptor works with my password, but it does not give me my mnemonic phrase, rather it gives a bunch of small numbers (lower than 200)  separated by ,

this is my output (numbers changed):
[{"type":"HD Key Tree","data":{"mnemonic":[108,97,110,115,145,111,110,35,108,111,98,115,116,101,114,32,102,101,129,32,102,114,111,103,32,99,104,111,105,99,101,32,98,97,99,104,111,108,111,114,32,112,97,116,99,104,32,119,117,115,116,32,112,97,112,101,114,32,185,115,111,108,97,116,101,42,107,112,105,115,111,100,101,32,97,117,116,118,179,110],"numberOfAccounts":1,"hdPath":"m/44'/60'/0'/0"}},{"type":"Ledger Hardware","data":{"hdPath":"m/44'/60'/0'","accounts":[],"accountDetails":{},"bridgeUrl":"https://metamask.github.io/eth-ledger-bridge-keyring","implementFullBIP44":false}}]

**Comment by mcmire** [comment]
We recently made a small change to how data is stored in the vault, and it seems we haven't updated the vault decryptor to match. The fix here should be easy to make. I'll take a look at this soon!

**Comment by foulerr** [comment]
Hi, any news about it? I desperately need this to recover my account. Good to see that you guys already know about this issue.

**Comment by nexon33** [comment]
I'm also waiting for it. Would be awesome if it could get fixed soon.

**Comment by InnaLogic** [comment]
So when is this going to be updated then?

**Comment by foulerr** [comment]
@mcmire Thank you. I've got 2 vaults and both are the same account and have the same 12 seed phrases, is it right?

**Comment by mcmire** [comment]
@foulerr Not sure! Is it right to you?

**Comment by mcmire** [comment]
By the way this issue should be fixed. Please let us know if you see any more issues!

**Comment by negati-ve** [comment]
Works like a charm! 
Thanks @mcmire 🔥
