### ISSUE TITLE
The link to How to Copy Your Vault Data doesn't work

### ISSUE THREAD

**Issue by dryruner** [MetaMask/vault-decryptor#4]
Hi dear developers,

The link(https://metamask.helpscoutdocs.com/article/22-how-to-copy-your-vault-data) says page not found/not public.  Can you please fix this issue? Thanks!

**Comment by adityanalge** [comment]
https://metamask.zendesk.com/hc/en-us/articles/360015289852-How-to-Copy-Your-Vault-Data
Maybe this public link will help you

**Comment by RemcoMi** [comment]
#10

**Comment by mcmire** [comment]
#10 was merged but it turns out that the bundled JavaScript wasn't updated. This has been done in both #37 and #38 so the link to the support article should work after either of those are merged.
