### ISSUE TITLE
Button disabled

### ISSUE THREAD

**Issue by myphotoir** [MetaMask/vault-decryptor#50]
I have entered my password and the vault object but the "Decrypt" button stays disabled. All I see in the code is to check that both contain data which they do. Any suggestions?

**Comment by legobeat** [comment]
Thank you for reporting.

1. Are you using "Database backup" (file upload) or "Paste text"?
2. If "Database backup": Which MetaMask version, OS version, and web browser version is the wallet originating from?
3. If "Paste text": Is the inserted text following a json text as resulting from following [this guide](https://support.metamask.io/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data)?

**Comment by mcmire** [comment]
Closing due to lack of response.
